BXCAN_BUSYWAIT_DELAY_SYSTEM_CORE_CLOCK auto retrieve
UAVCAN/platform_specific_components pull request #23
Opened 2020-11-09 10:31 UTC by sensometafisico

Added possibility to autonomously set BXCAN_BUSYWAIT_DELAY_SYSTEM_CORE_CLOCK as global variale SystemCoreClock when using ST's HAL.

2020-11-09 16:00 UTC, pavel-kirienko requested changes

2020-11-09 16:00 UTC, pavel-kirienko commented on stm32/libcanard/bxcan/src/bxcan.c
> +#ifdef USE_HAL_DRIVER
Please use `#if defined(USE_HAL_DRIVER) && USE_HAL_DRIVER` to properly handle the case where USE_HAL_DRIVER=0, as recommended by MISRA and similar standards.

2020-11-09 16:32 UTC, pavel-kirienko approved these changes

2020-11-11 09:15 UTC, TomDeRybel approved these changes
This is an elegant way of dealing with "setting the clock speed" issue I wasn't aware of. Nice!
I've already integrated in my local copy, and it works as expected.

2020-11-11 15:31 UTC, merged