Feature/can3 peripheral
UAVCAN/platform_specific_components pull request #25
Opened 2021-05-18 18:33 UTC by FalcioneE

Some STM32 microcontrollers include 3 CAN peripherals. Previously, Libcanard only supported the use of CAN1 and CAN2. This pull request would add support for CAN3 to Libcanard.

Changes:
_internal_bxcan.h: Include memory location of CAN3 config register
canard_stm32.h: Add build config macro for CAN3
canard_stm32.c: Make filter config generic so it will work for either CAN1 or CAN3

From Pavel: Some parameters have to be configured against the CAN1 instance, so replacing CANARD_STM32_CAN1 with BXCAN will break the driver (at least for some MCUs). This is covered in the Reference Manual.
Can you direct me to the reference manual please? 

This driver code works on my STM32F765VIT.

2021-05-20 13:12 UTC, pavel-kirienko requested changes
> Can you direct me to the reference manual please?

This is from the RM for STM32F10x:

<img width="694" alt="image" src="https://user-images.githubusercontent.com/3298404/118983789-7a628d00-b985-11eb-85fe-b5f6169cd418.png">

The RM for STM32F7 says the same thing:

<img width="622" alt="image" src="https://user-images.githubusercontent.com/3298404/118984113-d4635280-b985-11eb-8f57-542e015be118.png">

Did you actually test that the filters are functional? The RM says it shouldn't work. Even if it does, the driver would be reliant on undocumented behavior, which is usually unacceptable.

The patch also needs some formatting cleanup.

2021-05-20 18:12 UTC, FalcioneE commented
This is the ref manual I've been working from:
https://www.st.com/resource/en/reference_manual/dm00224583-stm32f76xxx-and-stm32f77xxx-advanced-arm-based-32-bit-mcus-stmicroelectronics.pdf

which includes this snippet: 
![image](https://user-images.githubusercontent.com/31711486/119028152-22bc2580-b975-11eb-904c-61e646ebb719.png)


CAN1 and CAN2 are multiplexed, and the configuration of some CAN2 settings are dependant on the CAN1 setup. CAN3 is entirely separate. I believe I've left the UAVCAN driver code such that the necessary CAN1 parameters are set up when CAN2 is selected.

2021-05-21 18:06 UTC, pavel-kirienko commented
Indeed, this special case requires special treatment. Observe though that you are accessing `F*` registers (such as `FM1R` etc) via the `BXCAN` macro, which resolves to CAN2 when CAN2 is selected, which breaks the driver. You could introduce an additional reference to the master CAN instance to solve this, such that it would resolve to CAN1 when either CAN1 or CAN2 are used; otherwise, it would resolve to CAN3.

Please also fix the formatting issues.

2021-05-21 19:06 UTC, FalcioneE commented
New commit pushed, let me know your thoughts. 

I think I caught most of the formatting differences, let me know if there are other things you need me to fix.

2021-05-21 19:39 UTC, pavel-kirienko requested changes

2021-05-21 19:39 UTC, pavel-kirienko commented on stm32/libcanard/canard_stm32.h
> +# define CANARD_STM32_USE_CAN3                                  1
```suggestion
# define CANARD_STM32_USE_CAN3                                  0
```

I don't imagine this configuration to be very common, so let the user choose the correct one explicitly.

2021-05-21 19:39 UTC, pavel-kirienko commented on stm32/libcanard/canard_stm32.h
> + * Setting this parameter when CAN1 is not available may not be detected at compile time!
```suggestion
```

AFAIK there are no chips where CAN1 is not available.

2021-05-21 19:39 UTC, pavel-kirienko commented on stm32/libcanard/canard_stm32.c
>  #endif
I suggest we add an `ifndef` check below that makes sure that BXCAN is defined. If not, the user forgot to define any of `CANARD_STM32_USE_CAN*`.

2021-05-21 19:39 UTC, pavel-kirienko commented on stm32/libcanard/canard_stm32.c
> +    BXCAN->FA1R = 0;
```suggestion
    FILTER_CONFIG_BXCAN->FA1R = 0;
```

2021-05-21 19:39 UTC, pavel-kirienko commented on stm32/libcanard/canard_stm32.c
> +        BXCAN->FilterRegister[filter_index].FR2 = mask;
```suggestion
        FILTER_CONFIG_BXCAN->FilterRegister[filter_index].FR1 = id;
        FILTER_CONFIG_BXCAN->FilterRegister[filter_index].FR2 = mask;
```

2021-05-21 19:39 UTC, pavel-kirienko commented on stm32/libcanard/canard_stm32.c
> +        BXCAN->FA1R |= 1U << filter_index;      // Enable
```suggestion
        FILTER_CONFIG_BXCAN->FA1R |= 1U << filter_index;      // Enable
```

2021-05-21 19:39 UTC, pavel-kirienko commented on stm32/libcanard/canard_stm32.c
> +    BXCAN->FA1R = 1;                                        // One filter enabled
I suggest we use `FILTER_CONFIG_BXCAN` here for clarity. The logic would not change but the intent should be more obvious.

2021-05-25 12:38 UTC, FalcioneE commented
Added ifndef to check that some CAN peripheral has been selected.

2021-05-25 13:47 UTC, pavel-kirienko requested changes
Thanks. You can request a review explicitly when ready by clicking this in the upper-right part of the page:

<img alt="image" src="https://user-images.githubusercontent.com/3298404/119508824-bed09d00-bd78-11eb-9da2-0eb6b691cd98.png">

2021-05-25 13:47 UTC, pavel-kirienko commented on stm32/libcanard/canard_stm32.c
> +    BXCAN->FA1R = 1;                                        // One filter enabled
Why not `FILTER_CONFIG_BXCAN`?

2021-05-25 13:47 UTC, pavel-kirienko commented on stm32/libcanard/canard_stm32.c
> +#error BXCAN not defined. Make a selection for BXCAN using the build config macros in canard_stm32.h.
```suggestion
# error BXCAN not defined. Make a selection for BXCAN using the build config macros in canard_stm32.h.
```

2021-05-25 13:59 UTC, pavel-kirienko approved these changes

2021-05-25 14:00 UTC, merged